# vim: ft=ansible:et:ts=2

- name: Configure external_collectors
  when: _scollector.external_collectors is defined
  block:
    - name: Create external collectors directory
      ansible.builtin.file:
        path: "{{ _scollector.external_collectors.dir }}"
        state: directory
        owner: root
        group: root
        mode: 0755

    - name: Create external collectors interval directories
      ansible.builtin.file:
        path: "{{ _scollector.external_collectors.dir }}/{{ item.interval }}"
        state: directory
        owner: root
        group: root
        mode: 0755
      with_items: "{{ _scollector.external_collectors.collectors }}"

    - name: Create external collectors
      ansible.builtin.template:
        src: "/etc/ansible/templates/external_collectors/{{ item.template }}"
        dest: "{{ _scollector.external_collectors.dir }}/{{ item.interval }}/{{ item.filename }}"
        owner: root
        group: root
        mode: 0750
      with_items: "{{ _scollector.external_collectors.collectors }}"

- name: Create scollector configuration file
  ansible.builtin.template:
    src: "{{ item }}.j2"
    dest: "/{{ item }}"
    owner: root
    group: root
    mode: 0640
  with_items:
    - "etc/bosun/scollector.conf"

- name: Configure OOM Score SystemD
  when: _scollector.oom_score_adj is defined
  block:
    - name: Check if SystemD Unit file for scollector exists
      ansible.builtin.stat:
        path: /etc/systemd/system/scollector.service
      register: stat_scollector_systemd

    - name: Set oom score for scollector in systemd
      ansible.builtin.lineinfile:
        dest: "/etc/systemd/system/scollector.service"
        state: present
        regexp: '^OOMScoreAdjust='
        line: "OOMScoreAdjust={{ _scollector.oom_score_adj }}"
        insertafter: '^\[Service\]'
      register: systemd_reload
      when: stat_scollector_systemd.stat.exists

    - name: Reload service definitions
      ansible.builtin.systemd:
        daemon_reload: yes
      when: systemd_reload.changed

- name: Announce external_collectors metric_metadata
  when: _scollector.external_collectors.metric_metadata is defined
  block:
    - name: Announce Meta data of external collector metrics # noqa ignore-errors
      run_once: true
      ansible.builtin.uri:
        method: POST
        url: "{{ _scollector.server.protocol | default('https') }}://{{ _scollector.server.ip }}:{{ _scollector.server.port }}/api/metadata/put"
        url_username: "{{ _scollector.auth.user }}"
        url_password: "{{ _scollector.auth.password }}"
        body_format: json
        body:
          - metric: "{{ item.metric }}"
            name: "rate"
            value: "{{ item.ratetype }}"
          - metric: "{{ item.metric }}"
            name: "unit"
            value: "{{ item.unit }}"
          - metric: "{{ item.metric }}"
            name: "desc"
            value: "{{ item.desc | default('') }}"
        status_code: 204
      with_items: "{{ _scollector.external_collectors.metric_metadata }}"
      ignore_errors: yes
